### ISSUE TITLE
noisy images with ximea-camera

### ISSUE THREAD

**Issue by Randy37773** [fastvideo/gpu-camera-sample#16]
Thank you for the software you provide.
I am trying to use gpu-camera-sample to acquire images from a ximea mu181cr-on camera. 
The images are very noisy, maybe the unpacking is expecting a different format. 
I tried to accumulate information [here](https://github.com/Randy37773/jetson-xavier-misc/tree/main/gpu-camera/fastvideo/log-noisy).

**Comment by fastvideo** [comment]
Thanks for your info.

As I can see from your logs, XIMEA CamTool software doesn't work with that camera either, though it should.
I think that you need to update the XIMEA package.

That's what we see from our log:
xiAPI: ---- Device opened. Model:MU181CR-ON SN:UPCBS2221027 FwF1:00.44 API:V4.25.14.00 ----
xiAPI: xiFAPI_Device::AcquisitionStop - ignored: acquisition is not running
It means that the software has found and has initialized the camera, but was unable to acquire images. We see the same with CamTool, so it's the question to XIMEA. CamTool software used to work with that camera.

By the way, that camera is noisy because it has too many pixels and they are very small.

**Comment by fastvideo** [comment]
Soon we will add support for XIMEA MU181CR-ON camera which has its own unpacking methods.

**Comment by fastvideo** [comment]
Please download the latest source codes for that project.
We've added two formats which are special for MU181CR-ON camera:
FGenTL_ITEM_GenTL_Image_Format_xiBayerGR10g160 and FGenTL_ITEM_GenTL_Image_Format_xiBayerGR12g192
This is the first release, so you will need to set bit depth to 10-bit or 12-bit and to check camera model. This is important because these formats are utilized just by that camera.
We carry on with the testing and of it's ok, we will create GPU-based uppacker for that camera as well.

**Comment by fastvideo** [comment]
That software now is working with XIMEA MU181CR-ON camera. Currently, raw unpacking is done on CPU. Soon we will add raw unpacking on GPU.
